# Generated by Django 3.2.4 on 2021-12-03 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=320, unique=True)),
                ('username', models.CharField(blank=True, default='', help_text='Just skip this', max_length=1)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('pilot', models.CharField(choices=[('1', 'Нет'), ('2', 'В прогрессе'), ('3', 'Пройден')], default='1', max_length=1)),
                ('success_pilot', models.BooleanField(null=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('thumbnail', models.TextField(blank=True, null=True)),
                ('product_stage', models.TextField(blank=True, null=True)),
                ('requires_cert', models.BooleanField(default=False)),
                ('team_size', models.PositiveIntegerField()),
                ('prior_organization', models.CharField(choices=[('1', 'Московский метрополитен'), ('2', 'Мосгорстранс'), ('3', 'ЦОДД'), ('4', 'Организатор перевозок'), ('5', 'Мостранспроект'), ('6', 'АМПП')], default='1', max_length=1)),
                ('use_cases', models.TextField(blank=True, null=True)),
                ('presentation_link', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SelectProjectRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_project', to='main.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomProjectRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pain', models.TextField(blank=True, null=True)),
                ('problem', models.TextField(blank=True, null=True)),
                ('what_if', models.TextField(blank=True, null=True)),
                ('why', models.TextField(blank=True, null=True)),
                ('whose_pain', models.TextField(blank=True, null=True)),
                ('period', models.TextField(blank=True, null=True)),
                ('tried', models.TextField(blank=True, null=True)),
                ('contacts', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
